version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"        
      time: "02:00"       
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore specific dependencies
    # ignore:
    #   - dependency-name: "Django"
    #     versions:
    #       - "5.1.4"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "02:00"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"


  - package-ecosystem: "github-actions"
    directory: ".github/workflows" 
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "02:00"
    open-pull-requests-limit: 5
