version: "3.8"

services:
  alphawebcrm:
    build: .
    image: localalphacrm
    container_name: alphawebcrm

    # Map host port 8000 to container port 8000
    ports:
      - "8000:8000"

    environment:
      # Local dev overrides
      USE_AWS_SECRETS: "false"
      DJANGO_DEBUG: "true"
      # add any additional env vars you need

    # If your Dockerfile doesn't already define a CMD or ENTRYPOINT
    # that runs Gunicorn on port 8000, you can specify it here:
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               gunicorn alphacrm.wsgi:application --bind 0.0.0.0:8000"
