services:
  web:
    build: .
    command: >
      bash -c "python manage.py collectstatic --noinput &&
             gunicorn alphacrm.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/app/staticfiles
      - /etc/letsencrypt/live/alphamminc.com/:/etc/letsencrypt/live/alphamminc.com/
      - /etc/letsencrypt/archive/alphamminc.com/:/etc/letsencrypt/archive/alphamminc.com/
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  db_data:
