
services:
  db:
    image: mysql:8.0
    container_name: alphawebcrm-db
    restart: always
    environment:
      MYSQL_DATABASE: my_local_db
      MYSQL_ROOT_PASSWORD: password  # Set the root password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  alphawebcrm:
      build: .
      image: localalphacrm
      container_name: alphawebcrm
      depends_on:
        - db
      ports:
        - "8000:8000"
      environment:
        # Local dev overrides
        USE_AWS_SECRETS: "false"
        DJANGO_DEBUG: "true"
        DB_NAME: my_local_db
        DB_USER: root
        DB_PASSWORD: password
        DB_HOST: db
        DB_PORT: 3306
      command: >
        bash -c "python manage.py collectstatic --noinput &&
                python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data:
