# Generated by Django 5.1.4 on 2025-01-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='record',
            new_name='client_record',
        ),
    ]
